### ISSUE TITLE
Graphics do not work on Windows 11

### ISSUE THREAD

**Issue by helgrima** [armak/Leviathan-2.0#1]
I installed Visual Studio 2022 and with that came Windows SDK  10.0.19041.0. 

_Editor_ build is working correctly, but _release_ and _snapshot_ builds do not work as expected. When building _release_ or _snapshot_ I get following error messages:

```
Error (active)	E1574	static assertion failed with "Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined."
Error	C2338	Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.
```
After googling I found out that error is related to _release_ and _snapshot_ build configurations: C/C++ -> Code Generation -> Struct Member Alignment

If I add **WINDOWS_IGNORE_PACKING_MISMATCH** variable to _release_ and _snapshot_ build properties under C/C++ ->Preprocessor -> Preprocessor Definitions building _release_ and _snapshot_ works.

Running _editor_ build on my Windows 11 is successful but running  _release_ or _snapshot_ on my Windows 11 only music is playing but graphics do not work. Only white screen appears. If I copy those builds to my Windows 10 machine they work just as expected.

Question is would it be easy fix to support newer SDK? Or is that even is the problem here?

**Comment by helgrima** [comment]
Ok, that was actually just some weird problem with my computer. And now graphics do work on my Windows 11 computer. I will close this and maybe make new issue about updating SDK version

**Comment by laurentlb** [comment]
For what it's worth, I also have the build error related to `WINDOWS_IGNORE_PACKING_MISMATCH`.
When I change the compiler flags to get it build, I also have a white screen in debug, snapshot or release, but it works fine in editor.
